#!/bin/bash

DOXY="/usr/local/Cellar/doxygen/1.8.20/bin/doxygen"

echo "INPUT = README.md . > create_doc/doxyfile.inc"
echo "FILE_PATTERNS = "*.md" "*.h" "*.cu" >> create_doc/doxyfile.inc"
echo "OUTPUT_DIRECTORY = doc/ >> create_doc/doxyfile.inc"

rm -r doc/html/

$DOXY "create_doc/Doxyfile"

rm -r docs/
mkdir -p docs/

cp -r -v doc/html/ docs



